name: Comprehensive Code Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Run Black
      run: black --check .
    - name: Run Pylint
      run: pylint **/*.py
    - name: Run Mypy
      run: mypy .
    - name: Check dependencies
      run: safety check
    - name: Run tests
      run: pytest
