name: Comprehensive Code Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install autopep8 black
    
    - name: Fix indentation with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive --recursive .
    
    - name: Run Black
      run: |
        black .
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"
    
    - name: Commit changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "Apply automatic formatting changes"
    
    - name: Push changes
      if: steps.git-check.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
    - name: Run Black check
      run: black --check .
    
    - name: Run Pylint
      run: pylint **/*.py
    
    - name: Run Mypy
      run: mypy .
    
    - name: Check dependencies
      run: safety check
    
    - name: Run tests
      run: pytest
