name: Python Package using Conda

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Set up Conda environment
      run: |
        conda init bash
        conda create --name myenv python=3.10 -y
        source ~/.bashrc
        conda activate myenv

    - name: Install dependencies
      run: |
        conda install --file requirements.txt

    - name: Lint code with flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest

